#!/bin/bash
# scan local network
# written by Adam Davenport, all rights reseved.

VInterface='wlp1s0'

# usage
[[ "$1" != "-f" ]] &&
        [[ "$1" != "-d" ]] &&
                [[ "$1" != "-s" ]] &&
                        [[ "$1" != "-p" ]] &&
                                echo "usage: scan [options]" &&
                                echo -e "options: [-f -d -p] <IP address>" &&                               echo -e "\t -f <fast scan>" &&
                                echo -e "\t -d <detailed scan>" &&
                                echo -e "\t -s <super-scan>" &&
                                echo -e "\t -p [IP] <port scan>" &&
                                echo "" && exit 1

function fast {
        sudo arp-scan -I $VInterface -l
}

function detailed {
#       sudo nmap -sS $(ipconfig getoption en1 router)/24;
#       sudo nmap -sP $(ipconfig getoption en1 router)/24;
        sudo nmap -Pn $(ipconfig getoption $VInterface router)/24
#       sudo nmap -sn $(ipconfig getoption en1 router)/24
}

function scan {
        s="$(ifconfig | grep 'broadcast'); a="${s[@]:6}"; : $(ping -qc 5 "$a")"; arp -al
}

function portscan {
        sudo nmap -Pn $p
}

### main ###
#sudo -v
#sudo chmod 777 /dev/bpf

# fast
[[ "$1" = "-f" ]] && fast

# detailed
[[ "$1" = "-d" ]] && detailed

# scan
[[ "$1" = "-s" ]] && scan

# portscan
[[ "$1" = "-p" ]] && p="$2" && portscan

#exit 0
